### ISSUE TITLE
java.lang.IllegalStateException at android.support.v4.util.Preconditions.checkState(Preconditions.java:130)

### ISSUE THREAD

**Issue by wangqi060934** [guenodz/recyclerview-selection-demo#2]
![untitled3](https://user-images.githubusercontent.com/1433283/41146997-b801fea6-6b37-11e8-848b-a18a4c1d4e0d.gif)
I just long press on an item to select it and click it to un-select it then.Now long press the item again will cause the app crash.
The logcat:
`    Process: me.guendouz.recyclerview_item_selection, PID: 1676
    java.lang.IllegalStateException
        at android.support.v4.util.Preconditions.checkState(Preconditions.java:130)
        at android.support.v4.util.Preconditions.checkState(Preconditions.java:142)
        at androidx.recyclerview.selection.GestureSelectionHelper.start(GestureSelectionHelper.java:76)
        at androidx.recyclerview.selection.SelectionTracker$Builder$4.run(SelectionTracker.java:742)
        at androidx.recyclerview.selection.TouchInputHandler.onLongPress(TouchInputHandler.java:136)
        at androidx.recyclerview.selection.GestureRouter.onLongPress(GestureRouter.java:95)
        at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
        at android.view.GestureDetector.-wrap0(GestureDetector.java)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by guenodz** [comment]
Actually, this is a bug related to the library itself which I already reported here : https://issuetracker.google.com/issues/78495471

**Comment by wangqi060934** [comment]
😯，Thanks
